spring:
  application:
    name: file-process-batch
  main:
    banner-mode: "off"
  batch:
    initialize-schema: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName : org.h2.Driver
    username: sa
    password: password
    
input-file-path : src/main/resources/input/tweet_data.json
output-file-path : src/main/resources/output 
log_url: 192.168.0.105
log_port: 24224
